tuirer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),

    path('', include('tuites.urls')),
    path('', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tuites/urls.py
from django.urls import path
from tuites.views import PostTuiteView, LikeTuiteView

app_name = 'tuites'

urlpatterns = [
    path('postar/', PostTuiteView.as_view(), name='post_tuite'),
    path('like/<int:pk>', LikeTuiteView.as_view(),name= 'like'),
]

users/urls.py
# URLs de users
from django.urls import path

# Escolher um dos dois
from users.views import ProfileView, ProfileEditView, UserLoginView, \
                        UserLogoutView, UserSignupView

app_name = 'users'

urlpatterns = [
    path('perfil/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('perfil/<int:pk>/editar/', ProfileEditView.as_view(), name='profile-edit'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('cadastro/', UserSignupView.as_view(), name='signup'),
]

core/models.py
from django.db import models

# Create your models here.

tuites/models.py
from django.db import models

from tuites.managers import TuitesManager


class Tuite(models.Model):
    content = models.CharField('Tuite', max_length=280)
    author = models.ForeignKey('users.User', verbose_name='Autor', on_delete=models.CASCADE, related_name='tuites')
    date_created = models.DateTimeField(auto_now_add=True)
    liked_by = models.ManyToManyField('users.User', blank=True)

    objects = TuitesManager()

    @property
    def likes_count(self):
        return self.liked_by.count()

    def get_author_username(self):
        return self.author.username

    def __str__(self):
        return f'{self.content}'

    class Meta:
        ordering = ('-date_created', )

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    picture = models.ImageField('Foto de perfil', default='/img/blank-pic.png')
    following = models.ManyToManyField('self', blank=True)

tuites/forms.py
from django import forms

from tuites.models import Tuite


class PostTuiteForm(forms.ModelForm):
    class Meta:
        model = Tuite
        fields = ('content', 'author')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['author'].initial = self.initial['user'].id
        self.fields['author'].widget = forms.HiddenInput()
        self.fields['content'].label = 'O que você está pensando?'

    def clean(self):
        cleaned_data = super().clean()

        content = self.cleaned_data.get('content')
        if 'Temer' in content:
            raise forms.ValidationError('FORA TEMER')

        if not self.initial.get('user') == cleaned_data.get('author'):
            raise forms.ValidationError('Não tente burlar o sistema!')

        return cleaned_data

users/forms.py
from django import forms
from users.models import User
from django.contrib.auth.forms import UserCreationForm

class UserSignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        user_exists = User.objects.filter(email=email).exists()
        if user_exists:
            raise forms.ValidationError('Um usuário com este e-mail já existe!')
        return email

core/views.py
from datetime import datetime

from django.http import HttpResponse
from django.shortcuts import render

from core.helpers import get_character_name, ip_info
from tuites.models import Tuite
from django.core.mail import send_mail
from django.conf import settings

def index(request):
    context = {
        'now': datetime.now(),
        'tuites' :  Tuite.objects.all(),
    }
    return render(request, 'home.html', context)

tuites/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, RedirectView

from tuites.forms import PostTuiteForm
from tuites.models import Tuite


class PostTuiteView(LoginRequiredMixin, CreateView):
    model = Tuite
    template_name = 'post_tuite.html'
    form_class = PostTuiteForm
    # reverse_lazy só será chamado 
    success_url = reverse_lazy('tuites:post_tuite')

    def get_initial(self):
        return {
            'user': self.request.user
        }

    # https://docs.djangoproject.com/en/2.0/ref/contrib/messages/
    def form_valid(self, form):
        messages.success (
            self.request,
            'Você postou um tuite!'
        )
        return super().form_valid(form)

class LikeTuiteView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        from_url = self.request.META.get('HTTP_REFERER')
        tuite_pk = kwargs.get('pk')
        user = self.request.user

        tuite = Tuite.objects.get(pk=tuite_pk)
        user_has_liked = tuite.liked_by.filter(pk=user.pk).exists()
        if user_has_liked:
            tuite.liked_by.remove(user)
        else:
            tuite.liked_by.add(user)
        return f'{from_url}#{tuite_pk}'

users/views.py
from django.views.generic import DetailView, UpdateView, CreateView
from users.models import User
from django.urls import reverse_lazy
from users.mixins import ProfileAccessMixin
from django.contrib.auth.views import LoginView, LogoutView
from users.forms import UserSignupForm


class ProfileView(DetailView):
    model = User
    template_name = 'profile.html'
    context_object_name = 'profile'


class ProfileEditView(ProfileAccessMixin, UpdateView):
    model = User
    fields = ('picture', 'username')
    template_name = 'profile_edit.html'
    
    def get_success_url(self):
        return reverse_lazy('users:profile', args=[self.object.pk])


class UserLoginView(LoginView):
    template_name = 'login.html'
    redirect_authenticated_user = True


class UserLogoutView(LogoutView):
    pass


class UserSignupView(CreateView):
    model = User
    form_class = UserSignupForm
    template_name = 'signup.html'
    success_url = reverse_lazy('tuites:post_tuite')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Tuirer</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/style.css' %}" />
    <script src="main.js"></script>

</head>
<body>
    <div id="navbar"> {% include  'includes/navbar.html' %} </div>
    <p>
        {% block body %}
        Hello.
        {% endblock %}
    </p>
    <footer>
        {% block footer %}
        <div class="copy">
             Copyright © 2018
        </div>
        <div id="mady">
            Made with  and  by Lucas Morais
        </div>
        {% endblock %}
    </footer>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block body %}

    {% if messages %}
        {% for message in messages %}
            <div>{{ message }}</div>
        {% endfor %}
    {% endif %}

    <div class="site-hero">
        <div class="overlay"></div>
        <div class="content">
            <h2>O que você está pensando?</h2>
            <p>Tuite para seus amigos.</p>
        </div>
    </div>
    <div class="tuites-home">
        {% for tuite in tuites %}
            {% include 'includes/card.html' %}
        {% endfor %}
    </div>
{% endblock %}

templates/includes/card.html
<div class="card">
    {% load tuite_likes %}
    <div class="card" id="{{ tuite.id }}">
        <p class="content">{{ tuite.content }}</p>
        <p class="likes">
            Curtido por 
            {% for user_liked in tuite.liked_by.all %}
                {{ user_liked }}
            {% empty %}
                ninguém
            {% endfor %}
        </p>
        <hr>
        <div class="author-and-likes">
            <a href="{% url 'users:profile' tuite.author.pk %}" class="author"> <!-- Adiciona link para o perfil do usuário -->
                <div class="author-avatar" style="background-image: url('{{ tuite.author.picture.url }}');"></div>
                {{ tuite.author }} 
            </a>
            <div class="date-created">
                {{ tuite.date_created }}
            </div>
            <div class="likes">
                <i class="far fa-heart"></i>
                0
                <a href="{% url 'tuites:like' tuite.pk %}">
                    {% tuite_liked_icon %}
                    {{ tuite.likes_count }}
                </a>
            </div>
        </div>
        </a>
    </div>

templates/includes/navbar.html
<nav>
    <div class="icone">
        <img src="static/img/pig.png" alt="">
        <h1>Tuirer</h1>
    </div>    
    <div class="navbar">
        <a href="{% url 'index' %}">Início</a>
        <a href="{% url 'tuites:post_tuite' %}">Postar Tuite</a>
        {% if user.is_authenticated %}
            <a href="{% url 'users:profile' request.user.pk %}">Olá, <b>{{ user.username }}</b></a>
            <a href="{% url 'users:logout' %}">Sair</a>
        {% else %}
            <a href="{% url 'users:login' %}">Entrar</a>
            <a href="{% url 'users:signup' %}">Cadastro</a>
        {% endif %}
    </div>
</nav>

templates/login.html
{% extends 'base.html' %}

{%  block body %}
    <form  method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <ipunt type="submit" value ="entrar"></ipunt>
    </form>
{% endblock  %}

templates/post_tuite.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block body %}
<div class="post-tuite-container">
    {% if form.errors %}
        {% for error in form.non_field_errors %}
            <p class="error">{{ error }}</p>
        {% endfor %}
    {% endif %}
    
    {% if messages %} 
        {% for message in messages %}
            <p class="message">{{ message }}</p>
        {% endfor %}
    {% endif %}
    
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            {% render_field field class="post-tuite-field" placeholder=field.label autofocus=True %}
        {% endfor %}
        <input type="submit" value="Postar Tuite">
    </form>
</div>
{% endblock %}

templates/profile.html
{% extends 'base.html' %}

{% block body %}
    <div
    class="profile-picture"
    style="background-image: url('{{ profile.picture.url }}');"
    ></div>
    {% if profile == request.user %}
        <a href="{% url 'users:profile-edit' request.user.pk %}">Editar perfil</a>
    {% endif %}

    <h2>{{ profile.username }}</h2>

    {% for tuite in profile.tuites.all %}
        {% include 'includes/card.html' %}
    {% endfor %}
{% endblock %}

templates/profile_edit.html
{% extends 'base.html' %}

{% block body %}
    <a href="{% url 'users:profile' request.user.pk %}">Voltar para seu perfil</a>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Enviar">
    </form>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block body %}
{{ form.errors }}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Registrar">
    </form>
{% endblock %}